name: 'eratani_dbt'
version: '1.0'
config-version: 2

profile: 'eratani'   # sesuaikan dengan nama profile di ~/.dbt/profiles.yml

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"       # directory untuk compiled SQL
clean-targets:              # files removed oleh `dbt clean`
  - "target"
  - "dbt_packages"

models:
  eratani_dbt:
    staging:
      +materialized: view
    fact:
      +materialized: table
    metrics:
      +materialized: table
